theme="polymer"
baseurl = "http://d.tflare.com/"
languageCode = "ja-jp"
title = "hiroyuki_tの日記"
MetaDataFormat = "toml"
paginate = 10 # optional
copyright = "Copyright (c) 2006 - 2017, hiroyuki_tの日記"
canonifyurls = true
publishdir = "docs"
disqusShortname = "http-d-tflare-com.disqus.com" # optional

[params]
  author = "hiroyuki_t"
  photo = "images/photo.png" # optional
  profile = "images/profile.png" # optional
  cover = "images/cover.png" # optional
  twitter = "taki_tflare" # optional
  github = "tflare" # optional
  googleAnalyticsUserID = "UA-84345073-1" # optional
